services:
  dev_api:
    build:
      context: .
      target: builder
    container_name: fastapi-dev-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"

  test_api:
    build:
      context: .
      target: builder
    container_name: fastapi-test-application
    environment:
      PORT: 9000
    ports:
      - '9000:9000'
    restart: "no"

  prod_api:
    build:
      context: .
      target: builder
    container_name: fastapi-prod-application
    environment:
      PORT: 10000
    ports:
      - '10000:10000'
    restart: "no"
