services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '9000:8000'
      - '10000:8000'
      - '11000:8000'
    restart: "no"
